# Metadata
name: Create GitHub Release

# Triggers
on:
  push:
    tags:
      - 'v*.*.*'

# Core
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git for releasing
        run: |
          git config --global user.email "ncryptsion@proton.me"
          git config --global user.name "NCryptsion"

      - name: Create zip of the repository (excluding .gitignore files)
        run: |
          git ls-files | zip release.zip -@

      - name: Upload release zip
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          files: release.zip